# #################################
#
# IMPORTANT: If you make any changes to this file, you must also update
# couchbase-server-black-duck-manifest.yaml in this directory!
#
# #################################

name: cbpy
channels:
  - ./conda-pkgs
dependencies:
# These are the packages we explicitly depend on.
# If you change these (packages OR versions), be sure
# to experimentally update the transitive dependencies below!
  - python=3.9.5*
  - msgpack-python=1.0.2
  - natsort=7.1.1
  - python-snappy=0.6.0
  - requests=2.25.1
# These are transitive dependencies of the above. We keep
# them pinned to avoid surprises when newer versions are
# installed. Where possible we pin them to the same version
# in cbdeps.
# Note: One way to create/update this list is to install a local miniconda3
# environment and activate it, then run
#    conda install python=3.9.2\* natsort=5.5.0 .....
#    conda update --update-all
#    conda install python=3.7.3\* natsort=5.5.0 .....
#    conda list
# This may need to be repeated on multiple platforms (Linux, Windows, and
# Mac). Also note that will list "conda" itself and packages that it
# depends on, which we don't want in the final cbpy installer; so take
# care when adding entirely new packages to the list below. Try leaving
# them out at first and see if cbpy builds OK.
  - brotlipy=0.7.0
  - ca-certificates=2021.4.13
  - certifi=2021.5.30
  - cffi=1.14.5
  - cryptography=3.4.7
  - idna=2.10
  - openssl=1.1.1k
  - pycparser=2.20
  - pyopenssl=20.0.1
  - pysocks=1.7.1
  - setuptools=52.0.0
  - six=1.15.0
  - snappy=1.1.8
  - sqlite=3.35.4
  - tk=8.6.10
  - tzdata=2020f
  - urllib3=1.26.4
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
# Finally, our "faked" dependencies. By convention these have an extra
# ".9" appended to the version number they're pretending to be. If we add
# more packages here in future, of course make sure they are NOT in the
# Black Duck manifest.
  - chardet=4.0.0.9
  - pip=21.0.1.9
  - readline=8.1.9
