#!/bin/bash

_old=`docker ps -a --filter name=builder --format "{{.ID}}"`
if [ x"$_old" != "x" ]
then
    echo "Deleting old builder"
    docker rm -f $_old > /dev/zero
fi

IMAGE=$(curl -sfL "https://raw.githubusercontent.com/couchbase/build-infra/master/docker-stacks/cv/cv-jenkins-agents.yml" | yq --yaml-fix-merge-anchor-to-spec=true e ".services.glibc228_large.image")

# You might want to limit the resources in your docker container.
# ex:
#   --cpus 6 \
#  --memory 12g \

docker run -d \
  -v ~/:${HOME} \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -p 8091-8095:8091-8095 \
  -p 11200-11220:11200-11220 \
  --dns 8.8.8.8 \
  --dns 4.4.4.4 \
  --name builder \
  --restart unless-stopped \
  --entrypoint '' \
  ${IMAGE} \
  tail -f /dev/null
