SET(CB_SPROXX_DEBUG "-g")
SET(CB_SPROXX_WARNINGS "-errfmt=error -errshort=tags -xlang=c99")
SET(CB_SPROXX_VISIBILITY "-xldscope=hidden")
SET(CB_SPROXX_THREAD "-mt")

IF ("${ENABLE_WERROR}" STREQUAL "YES")
   SET(CB_SPROXX_WERROR "-errwarn")
ENDIF()

SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CB_SPROXX_DEBUG} ${CB_SPROXX_WARNINGS} ${CB_SPROXX_VISIBILITY} ${CB_SPROXX_THREAD} ${CB_SPROXX_WERROR}")
