SET(CB_GXX_DEBUG "-g")
SET(CB_GXX_WARNINGS "-Wall -pedantic -Wmissing-declarations -Wredundant-decls -fno-strict-aliasing")
SET(CB_GXX_VISIBILITY "-fvisibility=hidden")
SET(CB_GXX_THREAD "-pthread")

IF ("${ENABLE_WERROR}" STREQUAL "YES")
   SET(CB_GXX_WERROR "-Werror")
ENDIF()

EXECUTE_PROCESS(COMMAND ${CMAKE_CXX_COMPILER} -std=c++11 OUTPUT_VARIABLE CB_CXX_LANG_OUT_MSG ERROR_VARIABLE CB_CXX_LANG_ERR_MSG)

SET(CB_CXX_LANG_VER "-std=c++11")
IF (CB_CXX_LANG_ERR_MSG MATCHES "unregocnized")
  SET(CB_CXX_LANG_VER "")
ENDIF()

SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CB_CXX_LANG_VER} ${CB_GXX_DEBUG} ${CB_GXX_WARNINGS} ${CB_GXX_VISIBILITY} ${CB_GXX_THREAD} ${CB_GXX_WERROR}")
