SET(CB_CLANGXX_DEBUG "-g")
SET(CB_CLANGXX_WARNINGS "-Qunused-arguments  -Wall -pedantic -Wmissing-declarations -Wredundant-decls -fno-strict-aliasing")
SET(CB_CLANGXX_VISIBILITY "-fvisibility=hidden")
SET(CB_CLANGXX_THREAD "-pthread")

IF ("${ENABLE_WERROR}" STREQUAL "YES")
   SET(CB_CLANGXX_WERROR "-Werror")
ENDIF()

EXECUTE_PROCESS(COMMAND ${CMAKE_CXX_COMPILER} -std=c++11 OUTPUT_VARIABLE CB_CXX_LANG_OUT_MSG ERROR_VARIABLE CB_CXX_LANG_ERR_MSG)

SET(CB_CXX_LANG_VER "-std=c++11")
IF (CB_CXX_LANG_ERR_MSG MATCHES "unregocnized")
  SET(CB_CXX_LANG_VER "")
ENDIF()

SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CB_CXX_LANG_VER} ${CB_CLANGXX_DEBUG} ${CB_CLANGXX_WARNINGS} ${CB_CLANGXX_VISIBILITY} ${CB_CLANGXX_THREAD} ${CB_CLANGXX_WERROR}")
