SET(CB_SPRO_DEBUG "-g")
SET(CB_SPRO_WARNINGS "-errfmt=error -errshort=tags -xc99=all")
SET(CB_SPRO_VISIBILITY "-xldscope=hidden")
SET(CB_SPRO_THREAD "-mt")

IF ("${ENABLE_WERROR}" STREQUAL "YES")
   SET(CB_SPRO_WERROR "-errwarn")
ENDIF()

SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${CB_SPRO_DEBUG} ${CB_SPRO_WARNINGS} ${CB_SPRO_VISIBILITY} ${CB_SPRO_THREAD} ${CB_SPRO_WERROR}")
SET(CMAKE_LINK_FLAGS "${CMAKE_LINK_FLAGS} ${CB_SPRO_LDFLAGS}")
