INCLUDE(FindPythonInterp)

IF (NOT DEFINED PYTHON_VERSION_MAJOR)
  SET(PYTHON_VERSION_MAJOR "0")
ENDIF()

IF (NOT DEFINED PYTHON_VERSION_MINOR)
  SET(PYTHON_VERSION_MINOR "0")
ENDIF()

IF(${PYTHON_VERSION_MAJOR} GREATER 2 OR ${PYTHON_VERSION_MINOR} GREATER 5)
  SET(COUCHBASE_PYTHON true)
ELSE()
  SET(COUCHBASE_PYTHON false)
  MESSAGE(STATUS "You should upgrade python so you can run tests!!!!!")
ENDIF()
